<a href="https://colab.research.google.com/github/UmarKhattab09/SKLEARNPIPELINES/blob/main/sklearn_pipeline_hyperparameter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##### SKLEARN PIPELINE

In [ ]:
from sklearn.pipeline import Pipeline
### FeatureScaling
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression


steps = [("Standard_Scaler",StandardScaler()),
         ("Classifier",LogisticRegression())
         ]

In [ ]:
steps

[('Standard_Scaler', StandardScaler()), ('Classifier', LogisticRegression())]

In [ ]:
pipe = Pipeline(steps)

In [ ]:
### Visualize Pipeline
from sklearn import set_config
set_config(display="diagram")

In [ ]:
### Creating A Dataset
from sklearn.datasets import make_classification
X,y=make_classification(n_samples=1000)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('Standard_Scaler', StandardScaler()),
                ('Classifier', LogisticRegression())])

In [ ]:
y_pred=pipe.predict(X_test)

In [ ]:
y_pred,y_test

(array([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
        0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
        0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
        1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
        0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
        0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
        1, 0]),
 array([1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
        0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
        0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
        1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
        0, 0, 0, 1, 1,

In [ ]:
### Example 2
### ----> Display a pipeline with StandScacler, DR and then estimator

In [ ]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [ ]:
steps=[("Scaling",StandardScaler()),
       ("PCA",PCA(n_components=3)),
       ("SVM",SVC())
]
pipe2 = Pipeline(steps)

In [ ]:
pipe2.fit(X_train,y_train)

Pipeline(steps=[('Scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVM', SVC())])

In [ ]:
pipe2['Scaling'].fit_transform(X_train)

array([[-0.18945269,  0.15209249, -0.97690646, ..., -0.47313186,
        -0.14378405, -0.91008797],
       [-0.92554225, -1.95616956,  1.08986284, ..., -1.51861822,
        -0.42424423,  0.88193784],
       [-0.57501214, -0.88297457,  0.88209942, ...,  0.71018618,
         0.04797113, -0.02476516],
       ...,
       [-2.17032199,  0.47830985, -0.47705974, ..., -0.19241636,
        -0.72930498,  0.54364869],
       [-2.17288728,  1.37930765, -1.08287956, ..., -1.11272495,
        -0.00575891, -1.63115793],
       [ 0.34663844,  1.45328782,  0.17290715, ..., -1.58166753,
        -0.32332908,  0.86007739]])

In [ ]:
### Column Transformer ----> Complex Example
from sklearn.impute import SimpleImputer # ----> For Numerical Feature,Basic
from sklearn.preprocessing import OneHotEncoder # ----> For Categorical Feature
from sklearn.compose import ColumnTransformer

In [ ]:
import numpy as np
numeric_processor=Pipeline( #----> Numeric Processing Pipeline
    steps=[
        ("Imputer",SimpleImputer(missing_values=np.nan,strategy="mean")),
        ("Scaler",StandardScaler())
    ]
)


In [ ]:
categorical_processor=Pipeline(
    steps=[
        ("Imputer",SimpleImputer(fill_value="missing",strategy="constant")),
        ("Scaler",OneHotEncoder(handle_unknown="ignore"))
    ]
)

In [ ]:

preprocessor=ColumnTransformer(
    [("Categorical",categorical_processor,["Gender","City"]),#---------> Categorical Feature
     ("Numeric",numeric_processor,["Age","Salary"])])

In [ ]:
preprocessor

ColumnTransformer(transformers=[('Categorical',
                                 Pipeline(steps=[('Imputer',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('Scaler',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['Gender', 'City']),
                                ('Numeric',
                                 Pipeline(steps=[('Imputer', SimpleImputer()),
                                                 ('Scaler', StandardScaler())]),
                                 ['Age', 'Salary'])])

In [ ]:
from sklearn.pipeline import make_pipeline
pipe=make_pipeline(preprocessor,LogisticRegression())

In [ ]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('Categorical',
                                                  Pipeline(steps=[('Imputer',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('Scaler',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Gender', 'City']),
                                                 ('Numeric',
                                                  Pipeline(steps=[('Imputer',
                                                                   SimpleImputer()),
                                                                  ('Scaler',
                                                                   StandardScaler())]),
                                                  ['Age', 'Salary'])])),
                ('logisticregression', LogisticRegression())])

## HyperParamter Tuning

In [ ]:
import numpy as np
from sklearn.pipeline import make_pipeline
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

In [ ]:
import seaborn as sns
df=sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
X=df.iloc[:,1:]
y=df['total_bill']
X

tip     sex smoker   day    time  size
0    1.01  Female     No   Sun  Dinner     2
1    1.66    Male     No   Sun  Dinner     3
2    3.50    Male     No   Sun  Dinner     3
3    3.31    Male     No   Sun  Dinner     2
4    3.61  Female     No   Sun  Dinner     4
..    ...     ...    ...   ...     ...   ...
239  5.92    Male     No   Sat  Dinner     3
240  2.00  Female    Yes   Sat  Dinner     2
241  2.00    Male    Yes   Sat  Dinner     2
242  1.75    Male     No   Sat  Dinner     2
243  3.00  Female     No  Thur  Dinner     2

[244 rows x 6 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [ ]:
## Pieplining
numeric_preprocessor = Pipeline(
    steps=[
        ("imputation_mean", SimpleImputer(missing_values=np.nan, strategy="mean")),
        ("scaler", StandardScaler()),
    ]
)

In [ ]:
categorical_preprocessor = Pipeline(
    steps=[
        (
            "imputation_constant",
            SimpleImputer(fill_value="missing", strategy="constant"),
        ),
        ("onehot", OneHotEncoder(handle_unknown="ignore")),
    ]
)

In [ ]:
preprocessor = ColumnTransformer(
    [
        ("numeric", numeric_preprocessor, [ "tip","size"]),
        ("categorical", categorical_preprocessor, ["sex", "smoker", "day", "time"]),
    ]
)

In [ ]:
preprocessor

ColumnTransformer(transformers=[('numeric',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['tip', 'size']),
                                ('categorical',
                                 Pipeline(steps=[('imputation_constant',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['sex', 'smoker', 'day', 'time'])])

In [ ]:
from sklearn import set_config
set_config(display="diagram")
pipe=Pipeline(steps=[("Preprocessor",preprocessor),
                     ("Regressor",RandomForestRegressor())])
pipe

Pipeline(steps=[('Preprocessor',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['tip', 'size']),
                                                 ('categorical',
                                                  Pipeline(steps=[('imputation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['sex', 'smoker', 'day',
                                                   'time'])])),
                ('Regressor', RandomForestRegressor())])

In [ ]:
pipe.fit(X_train,y_train)


Pipeline(steps=[('Preprocessor',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['tip', 'size']),
                                                 ('categorical',
                                                  Pipeline(steps=[('imputation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['sex', 'smoker', 'day',
                                                   'time'])])),
                ('Regressor', RandomForestRegressor())])

In [ ]:
y_pred=pipe.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.04250457158908294

In [ ]:
### USING GRID SEARCH CV NOW
import warnings
param_grid = {
    "Regressor__n_estimators": [200,500],
    "Regressor__max_features": ["auto", "sqrt", "log2"],
    "Regressor__max_depth": [4,5,6,7,8]
}

In [ ]:
from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(pipe, param_grid,n_jobs=-1)
grid_search.fit(X_train, y_train)
grid_search.best_params_

{'Regressor__max_depth': 5,
 'Regressor__max_features': 'log2',
 'Regressor__n_estimators': 200}

In [ ]:
pipe=Pipeline(steps=[("Preprocessor",preprocessor),
                     ("Regressor",RandomForestRegressor(max_depth=5,
                                                        max_features="log2",
                                                        n_estimators=200))])
pipe

Pipeline(steps=[('Preprocessor',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['tip', 'size']),
                                                 ('categorical',
                                                  Pipeline(steps=[('imputation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['sex', 'smoker', 'day',
                                                   'time'])])),
                ('Regressor',
                 RandomForestRegressor(max_depth=5, max_features='log2',
                                       n_estimators=200))])

In [ ]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('Preprocessor',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['tip', 'size']),
                                                 ('categorical',
                                                  Pipeline(steps=[('imputation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['sex', 'smoker', 'day',
                                                   'time'])])),
                ('Regressor',
                 RandomForestRegressor(max_depth=5, max_features='log2',
                                       n_estimators=200))])

In [ ]:
pipe.predict(X_test)

array([19.88042047, 27.25017452, 19.39586319, 20.42989428, 12.32540071,
       18.21053404, 13.61650675, 12.63238776, 24.52099177, 26.4050871 ,
       13.98317946, 16.58605796, 14.7442381 , 17.46142083, 28.36947464,
       18.3488744 , 19.34361167, 19.40821474, 15.9286868 , 15.66311235,
       21.09444121, 16.76487406, 27.41946832, 21.62479649, 15.8160774 ,
       12.70178656, 16.11124239, 17.46142083, 22.65341727, 18.40839612,
       15.71700273, 12.52334874, 13.44723161, 28.68991972, 19.4377244 ,
       15.87637309, 16.67325187, 20.1435195 , 19.84011604, 16.52559573,
       30.19889234, 16.20847412, 17.35573016, 14.44972753, 27.41946832,
       13.29513305, 28.4032044 , 14.8474867 , 17.1985648 ])

In [ ]:
r2_score(y_test,pipe.predict(X_test))

0.3502704810445586